spring:
    application:
        name: hospital-boot

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: alexandr
        password: krylov

    liquibase:
        change-log: db/changelog/changelog-master.xml
        enabled: true

    jpa:
        properties:
            hibernate:
                cache:
                    use_second_level_cache: true
                    region:
                        factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
                javax.cache:
                    provider: org.ehcache.jsr107.EhcacheCachingProvider


